### ISSUE TITLE
Would you consider adding an export for the empty UUID?

### ISSUE THREAD

**Issue by blake-mealey** [jchook/uuid-random#12]
When I work with UUIDs I find I often need to use the empty UUID (00000000-0000-0000-0000-000000000000) at times, and as I was using this library for generating my UUIDs I thought it would be nice to have it include the empty UUID as an export so I don't have to define it in my own code.

The API would be something like:

```js
const uuid = require('uuid-random');
const myEmpty = uuid.empty;
```

Would you consider a PR of this sort are you not interested?

**Comment by jchook** [comment]
Interesting! What kind of use case does this solve?

Foremost I'll point out that,

```js
uuid.test('00000000-0000-0000-0000-000000000000') === false
```

In other words, your "empty uuid" example doesn't satisfy [RFC 4122](https://tools.ietf.org/html/rfc4122).

After wrestling with SQL-based systems with `NOT NULL` columns that had "empty `DATETIME`" entries, I would highly recommend using `NULL` instead of 128 0 bits.

Even if your environment doesn't support `NULL`, or you feel afraid of the gotchas surrounding NULLable data types, if you represent your UUIDs as binary, then empty UUID simply becomes `0`, a very fine built-in constant :)

Finally, I'll add that adding an "empty UUID" constant to your own code seems very low-cost. For example,

```js
export const EMPTY_UUID = '00000000-0000-0000-0000-000000000000';
```

**Comment by blake-mealey** [comment]
Thanks for pointing that out, I didn't realize it was non-standard.

The case I just ran into was talking to a .NET-based API I cannot change which requires a `Guid` URL parameter but I don't need that parameter. Passing `null` to the API gives me this exception (from the .NET parameters parsing):

```
{
  "Message": "The request is invalid.",
  "MessageDetail": "The parameters dictionary contains a null entry for parameter 'canvasID' of non-nullable type 'System.Guid' for method ... An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter."
}
```

...but passing the empty Guid (00000000-0000-0000-0000-000000000000) to that parameter works as I want it to.

Also, in case you're not familiar with .NET, it provides `Guid.Empty` which returns the empty Guid.

You're absolutely right and I have pretty much that exact code in my project. It just feels like the kind of thing that should be defined in a library.

Thanks

**Comment by jchook** [comment]
Just a thought, even if you don't need it, you could still pass a unique `uuid()` for `canvasID`, right?

It seems that approach couldn't hurt, and also might better satisfy expectations of the remote API.

Because we advertise RFC 4122 compatibility, I think adding `uuid.empty` as you describe might complicate that claim.

I greatly appreciate your interest in making the library better and thanks for the suggestion.

**Comment by blake-mealey** [comment]
Makes sense and sounds good, thanks for discussing :)
